### ISSUE TITLE
asciidoc: preprocessor-directives to turn arc42help sections on an off

### ISSUE THREAD

**Issue by rdmueller** [arc42/arc42-template#101]
see https://github.com/docToolchain/docToolchain/issues/117 : 

in docToolchain, the templates already have been transformed.
The new template will enable a better handling of the asciidoc templates and migh enable a refactoring of the arc42-generator

**Comment by rdmueller** [comment]
yes, this would work. I usually remove the help contents when I am done with a chapter.

you approach would look something like this for each help section:

```
ifdef::arc42help[]
[.arc42help]
----
...
----
end::arc42help[]
```

I fear that this makes the template more complex than it is and it could scare people away...
but that is only my opinion

btw: the `[.arc42help]`-role adds a css class. So, we could toggle it via css

**Comment by ascheman** [comment]
> yes, this would work. I usually remove the help contents when I am done with a chapter.

I like to leave it in place for people coming later to the project to find some advice.

> you approach would look something like this for each help section:
> ...

Exactly, though I find only the `role` sections in the source, so I would wrap it around 

```asciidoctor
ifdef::arc42help[]
[role="arc42help"]
****
...
****
end::arc42help[]
```

> I fear that this makes the template more complex than it is and it could scare people away...

In my opinion it is a very small difference (and makes users aware of the power of AsciiDoctor).

> but that is only my opinion

Are there other stakeholders to ask for opinions? Should we ask people to vote for (or against) this change?

> btw: the [.arc42help]-role adds a css class. So, we could toggle it via css

I personally prefer a _native_ AsciiDoctor approach 😄

**Comment by rdmueller** [comment]
let's create an ADR!
we have several options...

- injected CSS to show help only as (?)-Bubbles on the right which expand on mouse over
- plain AsciiDoctor 2.0 html collapsible
- ifdef
- javascript show/hide
- new macro

right?

**Comment by ascheman** [comment]
The solution should work for generated PDF as well.
This reduces the number of options?

**Comment by gernotstarke** [comment]
is this issue still active? Does anyone still care?

Otherwise, I propose to close it.

**Comment by bohni** [comment]
That change in commit e946a29a56502e3b9c1050717581cfa3a360a6b6 polutes the plain template with emtpy blocks in every chapter 

```
ifdef::arc42help[]

endif::arc42help[]
```

**Comment by ascheman** [comment]
> That change in commit [e946a29](https://github.com/arc42/arc42-template/commit/e946a29a56502e3b9c1050717581cfa3a360a6b6) polutes the plain template with emtpy blocks in every chapter
> 
> ```
> ifdef::arc42help[]
> 
> endif::arc42help[]
> ```

Would you mind to open a new issue for this problem?

**Comment by bohni** [comment]
see #207 

Changes should also alter the revision...
