### ISSUE TITLE
explain setup of confluence template in cloud-hosted confluence

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#104]
please briefly explain how to import our confluence template
in a cloud hosted confluence...

(optimal would be a step-by-step, screenshot-supported docu...)

**Comment by rdmueller** [comment]
I guess on the cloud hosted instance, you are missing the admin access to import the template directly.

So, I only see a solution in importing it through the rest API via docToolchain. Unfortunately, we don't have much documentation about this yet.

Here is one fragment: https://doctoolchain.github.io/docToolchain/#_publish_on_confluence

A better documentation can be found here: https://arc42-template.atlassian.net/wiki/spaces/ARC42/overview?mode=global

In two weeks I will have some time which I could use to produce the step-by-step docu for the docToolchain approach

**Comment by gernotstarke** [comment]
closed, as issue is inactive and nobody else seems to care
