### ISSUE TITLE
wrong image link 

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#106]
https://github.com/arc42/arc42-template/blob/master/EN/asciidoc/src/05_building_block_view.adoc
contains a wrong image link.

Might be a problem on github only - need to verify in built-artifacts.

(problem was reported via [Twitter](https://twitter.com/leonardcapacete/status/968564623132721152))

**Comment by rdmueller** [comment]
I've just tested this with docToolchain - it builds fine, the image is referenced the right way.
So it seems to be the problem that github ignores the `imagesdir` definition from tha main file ...

**Comment by gernotstarke** [comment]
thanx Ralf, so this is github not respecting our imagedir def - I'll close this issue.
