### ISSUE TITLE
Asciidoctor template is missing default "css/style.css"

### ISSUE THREAD

**Issue by MarkusTiede** [arc42/arc42-template#112]
All asciidoctor templates are missing a default "css/style.css" leading to 

- warnings during build
- non-optimal output e.g. in HTML when just building and publishing the original template document

**Comment by gernotstarke** [comment]
Markus, thanx for the hint. Any chance you could provide a PR to improve this situation? 
(@rdmueller - did you know that?)

**Comment by gernotstarke** [comment]
close due to inactivity. Does not seem to be relevant any more.
