### ISSUE TITLE
Deutsche Hilfetexte  _gender-neutral_ formulieren

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#119]

**Comment by barthel** [comment]
Wie gehen wir mit der Rolle "Softwarearchitekt" um?
Sollen wir das "Gender-Sternchen" verwenden oder eine genderneutrale Umschreibung finden?

**Comment by barthel** [comment]
Ich würde mich dem Thema annehmen.

**Comment by barthel** [comment]
Nach dem Mergen müssen die Templates gebaut und committed werden.

**Comment by rdmueller** [comment]
mache ich sobald jemand gemerged hat. bauen und committen geht mittlerweile schnell.

**Comment by programming-wolf** [comment]
Ist drin, kannst bauen.

**Comment by rdmueller** [comment]
ok.

**Comment by rdmueller** [comment]
done and closed.
