### ISSUE TITLE
Deutsche Texte korrigieren/aufhübschen

### ISSUE THREAD

**Issue by programming-wolf** [arc42/arc42-template#120]
Es gibt noch einige unsaubere Textstellen, die korrigiert oder aufgehübscht werden können.

**Comment by barthel** [comment]
Welche?

**Comment by programming-wolf** [comment]
Ich hab das Ticket eigentlich für mich gemacht, um selbst etwas beizutragen. Darf ich es dir dann zum Review geben? :)

**Comment by barthel** [comment]
Gern. Ich werde mich dem gender-neutralem Textstil widmen :-).

**Comment by programming-wolf** [comment]
Ich habe einen PullRequest erstellt, aber ich kann dich leider nicht als Reviewer eintragen, @barthel :-/

**Comment by barthel** [comment]
Kein Problem. Ich schaue mir deinen PR mal an.
Danke!

**Comment by gernotstarke** [comment]
PR merged - ich schliesse den Issue

**Comment by rdmueller** [comment]
halt - die neuen Templates müssen och gebaut werden :-)

**Comment by programming-wolf** [comment]
Das könnten wir nach #119 machen, oder?

**Comment by rdmueller** [comment]
was wir haben, haben wir :-) Die Änderungen sind live...
