### ISSUE TITLE
Quality scenarios should be an early chapter

### ISSUE THREAD

**Issue by ewolff** [arc42/arc42-template#125]
IMHO quality scenarios are an important input to create a fitting architecture. However, the current template puts them in chapter 10. I would prefer to have it as chapter 3 or 4. That way the requirements are clear at the beginning (where they belong IMHO and where the constraints are). Also it makes quality a higher priority which does them more justice.

**Comment by gernotstarke** [comment]
Its the intention to extract the most important (one- or two handful) of quality scenarios into section 1.2 (as shown in the [arc42 docs](https://docs.arc42.org/section-1/)).

Keep the section 1 (the entry point to the architecture for many stakeholders) short, as proposed [here](https://docs.arc42.org/tips/10-1/), but include the very important and relevant scenarios.

Put the majority (aka the "rest") into section 10.

I second your opinion that these kinds of requirements REALLY shape most architectures, and should therefore: 
* be explained as early as possible
* have high priority

hope that clarifies the situation a bit...

**Comment by gernotstarke** [comment]
Second (pragmatic) option is the combination of 1.2 (top quality requirements) with 4 (solution strategy) within a single table:

* explain the quality scenarios in the left column of the table
* adjacent on the right explain the resulting solution approach(es), specific to THIS quality requirement

**Comment by gernotstarke** [comment]
Peter Hruschka and myself had an intensive discussion about your proposal, and decided (unanimously) NOT to change the section order:

* arc42 shall be no replacement for appropriate requirements documentation. In principle, quality requirements should also be contained in requirements!
* Section 1.2 (quality goals) should contain the most important of these Q-requirements, which should adress your issue!

We both dislike the idea of placing all quality scenarios prior to strategy, building blocks etc - as it makes reading way more unpleasant (people will have to skip most of the scenarios, as only a few of them will be architecturally relevant).

What we will do, though: Make it even more clear to EXPLICITELY formulate the topmost quality requirements in section 1.2, preferably as scenarios or similar operationable formulations!

Thanx @ewolff for your suggestion!
