### ISSUE TITLE
Wrong syntax for Textile tables

### ISSUE THREAD

**Issue by chseip** [arc42/arc42-template#127]
In Textile download you provide tables in HTML syntax. Those cannot be displayed with Redmine for example. This is an example for correct Textile syntax for tables which Redmine accepts:

`| 1 Spalte und 1 Zeile | 2 Spalte und 1 Zeile | 3 Spalte und 1 Zeile | 4 Spalte und 1 Zeile|
|\3=.Verknüpfen von Spalte 1-3 | 4 Spalte und 2 Zeile       |`

Screenhot:
![textile_tables](https://user-images.githubusercontent.com/3062968/67289342-bea65680-f4de-11e9-8034-e9ba43d7bdb7.png)

Please fix this as Textile cannot be used otherwise for Redmine.

**Comment by gernotstarke** [comment]
@chseip - thanx for notifying us.

Problem here: we generate the Textile version from our asciidoc source - and apart from you,
nobody seems to suffer from that table syntax (as nobody ever complained before!)

I personally have no idea why the generator (pandoc) produces the seemingly problematic syntax
(and surely won't find the time to research the topic) - sorry for that.

But: we very much welcome PR's with fixes or improvements.  Prerequisite: They should be fixes to the generator, NOT the generated artifacts.

In case there's anything we can do from our side to bring you up to speed with our generator (in principle, docToolchain), just let us know.

regards from Cologne, Gernot

**Comment by gernotstarke** [comment]
@rdmueller - you have any idea concerning Textile table syntax issues?

**Comment by chseip** [comment]
@gernotstarke Thanks for your fast reply. Didn't know of the pandoc usage and had a quick look into it. From what I found it seems to support real Textile tables, but all I could find was info on using Textile tables as input but not as output (cf. https://github.com/jgm/pandoc/issues/1922 and https://github.com/jgm/pandoc/issues/22)

**Comment by rdmueller** [comment]
I will check if there are options for oandoc to generate a different table style

**Comment by chseip** [comment]
Thanks, that'd be very helpful :-)

**Comment by rdmueller** [comment]
so, this is the task which creates textile:

https://github.com/arc42/arc42-generator/blob/master/subBuild.gradle#L243

If you want to, you could add an additional conversion via a PR, but I guess panoc will not be helpful for this.

**Comment by chseip** [comment]
@rdmueller Could/Will you try what was proposed over there?

**Comment by rdmueller** [comment]
so, it seems that a table definition from docBook like this

```xml
<informaltable frame="all"
    rowsep="1" colsep="1">
  <tgroup cols="2">
    <colspec colname="col_1" colwidth="33*"/>
    <colspec colname="col_2" colwidth="66*"/>
    <thead>
      <row>
```

will be translated to an HTML table in textile because of the width within the `colspec`

We now could create a lua filter or just replace it with a groovy script.

**Comment by rdmueller** [comment]
@chseip which language do you need? 
you will find a bunch of new templates (*textile2) in this folder https://github.com/arc42/arc42-template/tree/master/dist
The lua filter didn't work for me, because it works on the AST, so I used a groovy filter :-)

**Comment by chseip** [comment]
@rdmueller Looks fantastic, thanks so much! :-)

![textile2_tables](https://user-images.githubusercontent.com/3062968/68102906-0791de00-fed5-11e9-99a9-c458dac71542.png)
