### ISSUE TITLE
English image listing concepts contains German terms

### ISSUE THREAD

**Issue by ianmcderp** [arc42/arc42-template#128]
I noticed that the English image that lists cross-cutting concepts contains German terms. I would like to fix this - is there an automated way to generate the images from the xmind files? Or is this done purely by hand?

**Comment by gernotstarke** [comment]
ooh ooh, manually.... these mindmaps are rarely changed, therefore automation is imho not really needed...

**Comment by wilhem-meignan** [comment]
Suggestions:

Skalierung -> Scalability
Hochverfügbarkeit -> High availability
Monitoring, Logging, Protokollierung -> Monitoring, Logging

Isn't "Protokollierung" in German the same as "Logging" in English?

**Comment by gernotstarke** [comment]
PR welcome...

**Comment by Wallaby1999** [comment]
Is using PlantUML graphics generation (https://plantuml.com/de/mindmap-diagram) an option?

**Comment by wilhem-meignan** [comment]
I managed to correct the picture but not create a pull-request for it. I get a 403 error trying to push with git. I am probably doing something incorrectly since I have not contributed any PR on github yet.

**Comment by programming-wolf** [comment]
You’ve got to fork the repository and then create a pull request fr your repository to this one. 
Look here for details/help:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by wilhem-meignan** [comment]
Here a PR: https://github.com/arc42/arc42-template/pull/129

Thanks @programming-wolf for pointing me to the right documentation. I was missing forking the repository on github first ;-)

**Comment by ianmcderp** [comment]
Thanks for helping out to close this issue - and congratulations on your first PR on GitHub! :wink:

**Comment by wilhem-meignan** [comment]
Thanks! :smiley:
