### ISSUE TITLE
Remove inappropriate language in section 5.

### ISSUE THREAD

**Issue by andrekramer1** [arc42/arc42-template#130]
The building block section uses terms blackbox and whitebox. Consider using less loaded terms? Opaque & transparent.

**Comment by gernotstarke** [comment]
@andrekramer1 , thanx a lot for caring about arc42 and your interest.

in software engineering, the terms "black" and "white" are surely NOT loaded with inappropriate connotations - as "blackbox" and "whitebox" are strictly neutral expressions - not "one is better than the other".

In case you proposed to remove "master-slave" from any publication - I'd agree completely.

@peterhruschka and myself discussed your proposal, but could not find strong reasons to remove these terms.

**Comment by andrekramer1** [comment]
Sorry to hear that. Lot's of removal of backlist / whitelist terminology in computer science being done proactively now. While backbox may not be a very loaded term the fact that you invented & champion "whitebox" as a new term that has a quality (non-opaqueness)  that "blackboxes" don't have by your definition leaves you open to continued accusation. Please reconsider.
