### ISSUE TITLE
DOCX-files for download are broken

### ISSUE THREAD

**Issue by mk0** [arc42/arc42-template#138]
If you download and view the DOCX-files in english or german, they are almost empty. There is only the first page and then the document ends.

**Comment by programming-wolf** [comment]
I cannot confirm this. I downloaded both the plain German word document and the one with help, and they both contain all the chapters (plain 5 pages, with help 18 pages). Same with the English version (5 pages, 17 pages). 
I used macOS BigSur 11.3.1, Word for Mac 16.48. 

Maybe your download was corrupt or the extraction failed somehow?

**Comment by rdmueller** [comment]
Define "almost" empty.

This is the content of the english plain template downloaded from https://arc42.org/download

![image](https://user-images.githubusercontent.com/1856308/117939261-2d891180-b308-11eb-96ed-4c537fc22a4e.png)

looks good to me.

**Comment by mk0** [comment]
I am using OpenOffice. So this might be an issue on their side maybe. This is what I do get:

![grafik](https://user-images.githubusercontent.com/1453783/117976854-8371af80-b330-11eb-9b2e-dfd4e47aba38.png)

**Comment by gernotstarke** [comment]
we don't currently generate an OpenOffice version, but rely on compatibility between docx and openOffice...

My OpenOffice (4.1.6) simply crashes when trying to open the template...

sorry, no idea why, and currently no capacity to research this issue.

**Comment by gernotstarke** [comment]
upgraded to 4.1.10 (most recent version as of May 2021). Works fine now:
![image](https://user-images.githubusercontent.com/1233990/117981546-64c1e780-b335-11eb-92c1-30e5a8cf9a8c.png)

**Comment by gernotstarke** [comment]
close issue - seems resolved.
