### ISSUE TITLE
add ISO 25010 topics to help-text in section 1.2 

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#139]
briefly explain those topics in a diagram

**Comment by stefanleh** [comment]
Hi Gernot, 

there is a diagram and some explanations in english here: https://iso25000.com/index.php/en/iso-25000-standards/iso-25010 
For my currect architecture concept i needed this and created a mindmap using the content from the website above.
If interested i can share this.

Best regards, Stefan

**Comment by gernotstarke** [comment]
Hi Stefan, thanx for your suggestion. Problem with the iso25000 site is that it's not affiliated with ISO, and differs in wording from the official standard.

Additionally, I had a more explanatory diagram in mind. For the overview, I created one (with explanations taken from the original standard):

![1-2-iso-25010-topics-en Kopie](https://user-images.githubusercontent.com/1233990/135742393-3a3da636-6907-461b-b594-e61e9e0a0d8d.png)

**Comment by stefanleh** [comment]
Hi Gernot,

i wasn't aware that the iso25000 site uses an other wording. Thank you for pointing out. Now knowing there are differences maybe i can convince my employer to spend the 138CHF for the original ;)

Best regards, Stefan

**Comment by gernotstarke** [comment]
reading standards is one of those _rare pleasures_ I can easily live without - but sometimes it pays off. And yes, imho having the original ISO in your bag might help... (as does a towel and a protein bar). Enjoy your Sunday.

**Comment by gernotstarke** [comment]
I put the abovementioned diagram in docs.arc42.org, will include it in the template for V8

**Comment by gernotstarke** [comment]
done
