### ISSUE TITLE
add Gitpod yml to build html without local gradle/java installation

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#145]

**Comment by rdmueller** [comment]
today I tested the gitpod process and it worked fine - better than expected :-)

So, I get the feeling that this isse could be closed:

https://github.com/arc42/arc42-generator/blob/master/.gitpod.yml

**Comment by gernotstarke** [comment]
closed, gitpod is available for free on github. And Codespaces provide another way to build without local installation
