### ISSUE TITLE
DE/asciidoc/src/08_concepts.adoc: Broken sidebar 

### ISSUE THREAD

**Issue by bohni** [arc42/arc42-template#152]
In the german template are two closing delemiters of the help sidebar in chapter 8 of version 8.0

**Comment by gernotstarke** [comment]
thanx Stefan, I'm currently "on the road"and cannot update the generated files...

**Comment by gernotstarke** [comment]
therefore, I re-open the issue so I don't forget...

**Comment by rdmueller** [comment]
we still have to generate the template and deploy it.
@gernotstarke is it ok if I give it a try?

**Comment by rdmueller** [comment]
so, updated template has been deployed. It seems that this also fixed a problem with the headlines of the docx output.
