### ISSUE TITLE
Cross-cutting concepts vs cross-cutting concerns

### ISSUE THREAD

**Issue by sebastianpfischer** [arc42/arc42-template#154]
Hi @gernotstarke, hi @rdmueller,

After a quick check on "cross-cutting concept" on google, it seems like that the term "cross-cutting concern" is in broder use.
Is there a plan to align the arc42 template towards this naming or do you see some reasons to differentiate them?

Thanks in advance for your response.

**Comment by sebastianpfischer** [comment]
@almereyda, with no disrespect, it feels like ChatGPT :) But yes, in overall I agree with you ^^

**Comment by gernotstarke** [comment]
will close this issue, as discussed with @Hruschka we won't change the wording within the template or its documentation.
