### ISSUE TITLE
check order of image-usage and config-include

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#164]
first line:

`= image:arc42-logo.png[arc42] Template`

image is not found, as imagesDir has not yet been configured.

config is included in lines 25/26:
````
// configure EN settings for asciidoc
include::src/config.adoc[]
````

would it disturb the generator if we moved up this config-include to BEFORE the title?

**Comment by rdmueller** [comment]
no, I see no reason why it should disturb the generator.
