### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by rdmueller** [arc42/arc42-template#169]
the auto-build is currently broken https://github.com/arc42/arc42-template/actions/runs/2995530755

The problem seems to be the asciidoctor plugin version => https://stackoverflow.com/questions/69637205/cannot-locate-a-guava-jar-in-the-gradle-distribution

PR already prepared.

**Comment by almereyda** [comment]
After #170 got merged, the build errors disappeared at:

- https://github.com/arc42/arc42-template/actions

Suggesting to close here.

**Comment by gernotstarke** [comment]
thanx
