### ISSUE TITLE
Resolution of images doesn't work well in asciidoc editors

### ISSUE THREAD

**Issue by abentele** [arc42/arc42-template#178]
If you open the arc42 template files in IntelliJ IDE (with Asciidoc plugin), the images are not resolved in the Asciidoc preview view when opening a chapter file, e.g. the file 01_introduction_and_goals.adoc. This is because the images dir is not defined in every chapter file, but only in the main file.

adding this code block to the header of each file (alternatively include a file with this code) solves the problem for me:
```
// enable Asciidoc editors to resolve images when editing the file
ifndef::imagesdir[]
:imagesdir: ../images
endif::[]
```

Remark: because of the ifndef statement, it works as well when rendering the whole template.

**Comment by rdmueller** [comment]
Good idea.
We can even shorten this statement to

`ifndef::imagesdir[:imagesdir: ../images]`

**Comment by gernotstarke** [comment]
+1

@abentele would you mind to create a PR for that?

From my point of view, that change would improve ALL language versions.

**Comment by abentele** [comment]
thanks for your comments. Created a PR.

**Comment by gernotstarke** [comment]
whow, that was quick...
