### ISSUE TITLE
ISO 639 for language codes ('uk' instead of' ua' for Ukrainian)

### ISSUE THREAD

**Issue by tdankert** [arc42/arc42-template#202]
In my understanding, the language codes according to ISO 639 are used for the different translations.
This seems to be the case for all languages except for Ukrainian. 

I like to propose to use the correct code (uk) instead of the currently used one (ua)

**Comment by gernotstarke** [comment]
@Per-Starke could you please change the country code to UK (in the download-table and in the directory-name (/UA).

**Comment by gernotstarke** [comment]
done. Thanx again @tdankert for pointing out this quirk.
