### ISSUE TITLE
add textile output

### ISSUE THREAD

**Issue by rdmueller** [arc42/arc42-template#28]
In order to use the template for grails projects withouth asciidoc, a gdoc template is needed. gdoc is a subset of textile...

**Comment by gernotstarke** [comment]
suggestion: close / wontfix... imho Textile is rarely used (and should be abandoned in favor of AsciiDoc anyway...)

**Comment by rdmueller** [comment]
you are right - textile is rarely used, but we also already have a textile template :-)
