### ISSUE TITLE
create PDF as format

### ISSUE THREAD

**Issue by rdmueller** [arc42/arc42-template#35]
...but I guess it only makes sense for the with-help version

**Comment by rdmueller** [comment]
phantomjs could be used to print html as pdf.
pandoc needs latex to create pdf

**Comment by gernotstarke** [comment]
pdf output is planned for asciidoctor in the near future... (currently alpha):

http://asciidoctor.org/docs/convert-asciidoc-to-pdf/

**Comment by masch70** [comment]
I just recently successfully used asciidoctor-pdf to create a pdf-version of Arc42-Template based architecture documentations. Although in Alpha still, the only really "visible" drawback was the missing admonition icons for e.g. notes. Support thereof is already on the roadmap and not "killing" the benefit of having only one readable document for the stakeholders without the complex detours through docbook et al.

**Comment by rdmueller** [comment]
jsut stumbled upon https://github.com/asciidoctor/asciidoctorj/tree/master/asciidoctorj-pdf and https://github.com/asciidoctor/asciidoctor-fopub . I'll take a look at those options and see which ist the easiest to use.

**Comment by gernotstarke** [comment]
close this - pdf as output format is not useful for practical work (as nobody will EDIT an architecture documentation in pdf)
