### ISSUE TITLE
html version en is missing all images

### ISSUE THREAD

**Issue by rdmueller** [arc42/arc42-template#45]

**Comment by gernotstarke** [comment]
will have a look into this...

**Comment by gernotstarke** [comment]
Build file compiles only de version...

Need to refactor... Maybe we phone after Easter...

Gernot


Dr. Gernot Starke
+49-177-7282570
gs@gernotstarke.de
www.gernotstarke.de

Von einem mobilen Geraet gesendet - bitte verzeihen Sie eventuelle Tippfehler.
