### ISSUE TITLE
template contains non-UTF-8 characters

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#48]
in directory "plain-without-help", all "Umlauts" are causing non-UTF-8 aborts with asciidoctor (on Mac OS)

Seems we have a Windows/Mac issue again...

**Comment by rdmueller** [comment]
ok. thought that Max OS is comparable to linux - I just tried to build a clean version of this repository on Win8, Ubuntu and Mint Mate. No (real) problems.

Can you please post your error message?

**Comment by rdmueller** [comment]
wrong templates have been removed
