### ISSUE TITLE
include (sample) gradle + maven buildfile into asciidoc distribution...

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#51]
so that prosective users can immediately start...
(with at least java or maven installed)

**Comment by rdmueller** [comment]
may I add Grails to the list of sample build systems? I know, it is not as popular as maven or gradle... wait - Grails 3 is based on gradle :-)

IMHO, a ZIP with a full gradle/maven project would be great, but what about starting with some documentation on how to use the template with build system x and a link to a gist containing the needed sample build file.

We could use the wiki at https://github.com/arc42/arc42.github.io/wiki to get started.

**Comment by gernotstarke** [comment]
imho gradle and maven are way more popular, so we should have at least those two...

**Comment by barthel** [comment]
I like the wiki idea instead of providing a ZIP file.

We could deploy show POM (Maven) an Gradle configuration examples in wiki beside a small HowTo section.

An additional and maybe more practical idea is to provide an specific [Maven archetype](https://maven.apache.org/guides/introduction/introduction-to-archetypes.html) to setup a new project including the arc42-template and the required Plugins and file/directory structure.

**Comment by rdmueller** [comment]
I am currently working on an gradle and maven archetype but I am not an expert regarding both tools. First blog posts are available on http://rdmueller.github.io

**Comment by gernotstarke** [comment]
@rdmueller - we could provide links to our HHGDAC examples...  that could be done with an improved readme.md... will look into updating docs.arc42.org accordingly.

**Comment by rdmueller** [comment]
wow. this now ooen for quite a long time...
the gradle archetype evolved into @docToolchain . But I do agree that better examples on how to use it would help...

**Comment by gernotstarke** [comment]
I added a (really frugal) gradle build, currently only for EN.
Could easily be changed for another language, will add this to readme

**Comment by gernotstarke** [comment]
good enough, need to debug the language settings some day

**Comment by gernotstarke** [comment]
I added a (really frugal) gradle build, currently only for EN.
Could easily be changed for another language, will add this to readme
