### ISSUE TITLE
create lazybones template 

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#55]
to setup an empty asciidoc-based arc42 as simple as possible...

see https://github.com/pledbrook/lazybones

**Comment by gernotstarke** [comment]
@rdmueller : you guys using lazybones anywhere in productive environments?
I'm quite impressed with its application within the Griffon framework- it does some heavy lifting there...
regards (from Zurich), Gernot

**Comment by rdmueller** [comment]
@gernotstarke : yes, lazybones is cool. already started to work on an arc42 template, but then I was distracted by some other project.

We should definitifly work on this!

**Comment by rdmueller** [comment]
I just remember the problem I faced:

lazybones helps to kickstart a new application. e.g. you have an empty folder.

With arc42, you want to _add_ documentation to a project. Thus you have to know which type of project (gradle, maven, ant?) and have to modify the build script.

But it would be already a good start if we create an ampty arc42 project which then can be merged manually into another project or jsut used stand-alone..

**Comment by gernotstarke** [comment]
U're late-nighter and early-bird... rare combination :-)

good point - imho kickstarting an arc42 (asciidoc-gradle) project would be sufficient.

**Comment by gernotstarke** [comment]
closed as not relevant... people tend to "copy" an example... and creating the lazybones template would be quite some effort :-)
