### ISSUE TITLE
LaTeX Template für arc42

### ISSUE THREAD

**Issue by wuethrich44** [arc42/arc42-template#56]
In meiner Schule benutze ich LaTeX um Dokumente erstellen und zurzeit dokumentiere ich ein Projekt von mir mit arc42. Deshalb habe ich eine Vorlage in LaTeX für eure Architekturdokumentation erstellt. Sie befindet sich auf Github unter folgendem Link:

https://github.com/wuethrich44/arc42-latex

Ich hoffe das ist oke für euch (Lizenz) und wenn ihr wollt könnt ihr das Template bei eurem Wiki hinzufügen. Ich werde das Template laufend an das Confluence-Template anpassen und bei Bedarf noch eines für Englisch hinzufügen.

**Comment by rdmueller** [comment]
Das Template in LaTeX ist erstmal eine coole Idee! 
Werde mal sehen, dass ich es verlinke.
In diesem Repository versuchen wir alle anderen Template-Versionen aus dem AsciiDoc Template zu erzeugen. Dadurch fällt die Pflege leichter. Wie ich gerade gesehen habe gibt es schon ein entsprechendes Backend:

- https://github.com/asciidoctor/asciidoctor-latex
- https://github.com/asciidoctor/asciidoctor/issues/681

Haettest Du Lust Dir das mal anzusehen? Dann würde die manuelle Pflege wegfallen...

**Comment by wuethrich44** [comment]
Ok super ich werde mir das bei Gelegenheit mal anschauen und einen PR bereitstellen sobald es geklappt hat.

**Comment by gernotstarke** [comment]
danke für Deine/Eure Mithilfe an arc42!
@wuethrich44 : möchtest Du Dein Projekt vielleicht als Beispiel für arc42-Nutzung
veröffentlichen? Wir suchen bei arc42 immer Beispiele...und in LaTeX haben wir bisher 
noch nichts.
vG Gernot

**Comment by wuethrich44** [comment]
Die Arbeit ist erst in 3 Monaten abgeschlossen und dann werde ich mal schauen was sich veröffentlichen lässt, weil wir closed source entwickeln. Ich werde mich melden sobald ich mehr weiss.

**Comment by Christoph460** [comment]
Hallo, 
Wir würden in der Ausbildung gerne ein Latex Template verwenden, gibt es dabei eine aktuelle Version, gibt es diese auch auf English. 
Danke für eure Hilfe!

**Comment by gernotstarke** [comment]
Hi Christoph, "offiziell" supporten wir LaTeX nicht.
Aber vielleicht interessiert Dich ja https://leanpub.com/arc42byexample... das könnte Dir ggfs. ein paar Anregungen für Deine Arbeit geben.. (und ist Englisch...)

vG Gernot

**Comment by Christoph460** [comment]
Ok, Danke für deine Antwort. Derzeit habe ich eher ein wirkliches latex template gemeint, Trotzdem danke

**Comment by rdmueller** [comment]
Hi! Es gibt für asciidoctor ein LaTex backend: https://github.com/asciidoctor/asciidoctor-latex

Man könnte also das Template konvertieren...

**Comment by wuethrich44** [comment]
Ich habe versucht das Template mit dem [LaTex Backend ](https://github.com/asciidoctor/asciidoctor-latex) zu konvertieren. Dazu müsste man aber ein Rubygem installieren und ich habe nicht herausgefunden wie das mit dem Gradle-Plugin funktioniert. 

Mir ist es aber gelungen das Template mit `pandoc` zu konvertieren. Allerdings müsste ich vor und nach dem Dokument noch Text einfügen.

@rdmueller Kennst du eine Möglichkeit ein Rubygem mit dem Gradle-Plugin zu installieren oder Text vor und nach dem Dokument mit Pandoc einzufügen?

**Comment by rdmueller** [comment]
@wuethrich44 - für maven habe ich mal gesehen, dass es da einen speziellen Tag gibt.
Für Gradle habe ich das hier gefunden: http://asciidoctor.org/docs/asciidoctorj/#gem_path
u.U. müsste man mal ohne das asciidoc plugin arbeiten und asciidoctorj direkt aufrufen, nachdem man den gem_path gesetzt hat: http://saltnlight5.blogspot.de/2013/08/how-to-convert-asciidoc-text-to-html.html

Text vor und nach dem pandoc würde ich einfach mit einem kleinen groovy-script erledigen...

Das LaTex-Backend ist aber sicher eleganter :-)

**Comment by rdmueller** [comment]
Thanx to @wuethrich44 , this issue can now be closed. Template is available for download at http://http://arc42.github.io/
