### ISSUE TITLE
create confluence space from adoc (or another intermediate format)

### ISSUE THREAD

**Issue by rdmueller** [arc42/arc42-template#6]
create a gradle build step which converts the subset of adoc which is sued by arc42 into a confluence space.
Target will be the current confluence on demand version (5.3), but goal will be to support as many older versions as possible (let's see what the confluence api will provide us)

let's define some acceptance criteria:
A1: export should look "nice"
A2: if possible, a new export should only add to the confluence history when pages have been changed
A3: images have to be exported

**Comment by gernotstarke** [comment]
I'd be VERY interested to add confluence to the supported build targets:

* it needs to be a version that can be "imported" into an existing space
(so it does not need to be a space on its own)
* the "with-help" version should contain help as "show-on-demand"
* we might even skip the "plain" version...

**Comment by rdmueller** [comment]
the docToolchain can handle confluence - but not as import:

It generates HTML from AsciiDoc and publishes this as several pages to confluence. Help is published as "show-on-demand".

This enables you to

- specify a page prefix... interesting for users who can't create new confluence spaces (corporate confluence)
- export the confluence space afterwards (may be could automate this...)
- docToolchain is independent of the confluence version - only on the REST API

**Comment by gernotstarke** [comment]
we can create confluence space - therefore I close this...
