### ISSUE TITLE
Konzepte-Kapitel kürzen

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#60]
Konzepte-Themen primär als Checkliste aufnehmen, keine weiteren Erläuterungen mehr.

**Comment by rdmueller** [comment]
Das vereinfacht das Template und unterstreicht den Checklisten-Charakter des Kapitel 8.
Auf der anderen Seite erleichtern die Erläuterungen den Einstieg in die Dokumentation mit arc42...

**Comment by gernotstarke** [comment]
1. Erläuterungen zu den Themen komplett aus Template raus, in "Hilfe" verschieben. 
2. als Vorschläge aufnehmen:
    * Batch-/Stapel-Verarbeitung, 
    * Drucken, 
    * Reporting und 
    * Archivierung.

**Comment by gernotstarke** [comment]
in V7 it has been REALLY shortened :-)

Ausführliche Erklärungen wandern in Hilfe und/oder FAQ.
