### ISSUE TITLE
Link to HtmlSanityChecker on Confluence LandingZone is broken

### ISSUE THREAD

**Issue by Towabohu** [arc42/arc42-template#68]
Moin, moin arc42-Team,

on the confluence landing page (http://confluence.arc42.org/display/LANDINGZON/landing+zone) the Link to the introductory example, the HtmlSanityChecker, is broken.

Probably it should be: http://aim42.github.io/htmlSanityCheck/hsc_arc42.html

Best wishes and nice x-mas

Mischa

**Comment by gernotstarke** [comment]
the landing page has been superseeded by a new version, link has been corrected.

thx, Mischa, for reporting...
