### ISSUE TITLE
build failure: "gradle arc42" fails with fatal exception...

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#70]
MadZorg42:arc42-template gstarke$ gradle arc42

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/gstarke/projects/arc42/arc42-template/build/src_gen/DE/asciidoc/plain/build.gradle' line: 28

* What went wrong:
A problem occurred evaluating project ':/build/src_gen/DE/asciidoc/plain/'.
> Declaring custom 'build' task when using the standard Gradle lifecycle plugins is not allowed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by gernotstarke** [comment]
commented out the following

    task build () << {}

then it worked...

**Comment by gernotstarke** [comment]
I've NO idea why the empty task was included ( @rdmueller -> you wrote that code...),
if nobody objects, I'll remove it...

**Comment by rdmueller** [comment]
nobody objects. I was included to make it work with netbeans, but this should be an old workaround

**Comment by rdmueller** [comment]
it seems that you get the exception because you use a newer gradle version.

the gradlew works fine.

**Comment by gernotstarke** [comment]
not great, but I close this one. As long as the gradlew works, it's acceptable.
