### ISSUE TITLE
Generator bug: Abschnitt "Form" fehlt bei Kontextabgrenzung DE

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#73]

**Comment by rdmueller** [comment]
an dieser Stelle?
http://arc42.github.io/template/de/arc42-template.html#section-system-scope-and-context

**Comment by gernotstarke** [comment]
its in the v70 branch, we found the bug in the generated docx, didn't check in other formats

**Comment by rdmueller** [comment]
Ok ist the html ok? So maybe an update of pandoc  might fix this...

**Comment by gernotstarke** [comment]
will check this afternoon...

**Comment by gernotstarke** [comment]
the docx has really strange bugs. I removed a few space-characters from the asciidoc source, now the corresponding section in docx reads (now the headling "Form" is missing...):

Kontextabgrenzung
Inhalt.
Die Kontextabgrenzung grenzt das System von allen Kommunikationspartnern (Nachbarsystemen und Benutzerrollen) ab. Sie legt damit die externen Schnittstellen fest.
Differenzieren Sie fachlichen Kontext (fachliche Ein- und Ausgaben) und technischen Kontext (Kanäle, Protokolle, Hardware), falls nötig.
Motivation.
Die fachlichen und technischen Schnittstellen zu Kommunikationspartnern gehören zu den kritischsten Aspekten eines Systems. Stellen Sie sicher, dass Sie diese komplett verstanden haben.
¥	Diverse Kontextdiagramme
¥	Listen von Kommunikationspartnern mit deren Schnittstellen.
Fachlicher Kontext

**Comment by gernotstarke** [comment]
seems to be asciidoctor issue:
The following works:

    .Form
    Alternativ als Diagramm und/oder Tabelle:

    * Diverse Kontextdiagramme
    * Listen von Kommunikationspartnern mit deren Schnittstellen

and the following does NOT work (it does not show the heading "Form":

    .Form
    
    * Diverse Kontextdiagramme
    * Listen von Kommunikationspartnern mit deren Schnittstellen

due to the sensitivity of the buildscript, I cannot simply update to asciidoctor-1.5.5... :-(

**Comment by gernotstarke** [comment]
btw - I'm running pandoc 1.19.1

**Comment by gernotstarke** [comment]
IS an asciidoc issue - we have to separate a "unnumbered list" from a heading by at least
one line of plain text...
