### ISSUE TITLE
currently image-directories are handled strangely...

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-template#77]
There are currently two dirs:

    ./src/DE/images, 
    ./src/images

the first build step (createTemplatesFromGoldenMaster) copies over
the contents from the DE/images dir to src_gen...

imho handling would be easier to have ONE location that's outside
the DE directory, but that would mean to update the build process accordingly...

**Comment by gernotstarke** [comment]
I deleted the "outer" directory to remove duplication. Build is now clean, albeit strange (to have EN images copied over from DE directory).

**Comment by rdmueller** [comment]
There is now an "outer" directory which contains all images for the generator.
It could be that for development of the templates, these images have to be copied down to the corresponding adoc folder. 
I guess that was the reason why the structure was  so strange...

**Comment by gernotstarke** [comment]
thx
