### ISSUE TITLE
Blackbox Template - typing error

### ISSUE THREAD

**Issue by Humbalan** [arc42/arc42-template#79]
1. In the info box table row "Open issues": missing ">" at the end of the line. 
2. In the 2nd info box "for confluence users": missing closing quotation marks after "blackbox-table
3. Red text "ICH FINDE DIE ZWEITE VARIANTE NICHT!!": not clear that the heading at the end of the page (Blackbox <X> (headings)) is the mentioned "ZWEITE VARIANTE".

**Comment by gernotstarke** [comment]
Thx, which format (docx, markdown, html..) are you referring to?

Regards, Gernot 

Dr. Gernot Starke
+49-177-7282570
gs@gernotstarke.de
www.gernotstarke.de

Von einem mobilen Geraet gesendet - bitte verzeihen Sie eventuelle Tippfehler.

**Comment by Humbalan** [comment]
Thank you for your quick answer. I forgot to write that I am working with the Confluence template for Confluence 5/6

**Comment by gernotstarke** [comment]
@Humbalan : We're **very** short of releasing arc42 version 7 - a major overhaul of nearly everything involved:  we keep the structure completely intact, but refactored all the help-texts.

The confluence template will (hopefully within the next 2-3 weeks) be completely generated from
the asciidoc source.

You can get a preview on http://docs.arc42.org.

**Comment by Humbalan** [comment]
Had a look at it. tkx for the info. The new version containes a lot of helpfull information!
