### ISSUE TITLE
create confluence output

### ISSUE THREAD

**Issue by rdmueller** [arc42/arc42-template#80]
- [x] get confluence cloud instance
- [x] test a first export with docToolchain

https://arc42-template.atlassian.net/wiki/collector/pages.action?key=DOC

This is the "flat" export - one page per chapter. There is also a "deep" export which creates a deeper structure.

currently template V6

**Comment by gernotstarke** [comment]
how can I further motivate you?? (in addition to stalking the issue tracker...)

**Comment by gernotstarke** [comment]
why not try with V7...

**Comment by rdmueller** [comment]
Progress! V6 and V7 is out and it helped to discover and fix a bug in docToolchain.

Now I need to fix the missing first page...
