### ISSUE TITLE
Broken link 2.3.20. Stakeholder Analysis

### ISSUE THREAD

**Issue by monofone** [arc42/arc42-template#81]
Beneath the **References** is a link placed _arc42 example stakeholder table_ pointing to https://github.com/arc42/arc42-template/blob/master/src/DE/asciidoc/plain/src/kap01.adoc, this link gives a 404 on github.

Nice write though

**Comment by rdmueller** [comment]
Thanx for the feedback.
Do you have a link to the file where the 404 is in?

**Comment by monofone** [comment]
https://aim42.github.io/#Stakeholder-Analysis


-------- Original message --------

**Comment by monofone** [comment]
Oh,  I found the right place for the Issue, I didn't realized that arc42 and aim42 are different organisations. New Issue at https://github.com/aim42/aim42.github.io/issues/1
