### ISSUE TITLE
Rhapsody format

### ISSUE THREAD

**Issue by ecsgz** [arc42/arc42-template#87]
...request for format for other modelling tools similar to Enterprise Architect format (http://arc42.org/download): here, a format for IBM Rational Rhapsody.

Thank you for reading and maybe considering this issue/request!

**Comment by gernotstarke** [comment]
thx for your request.

Currently none of our committers and contributors is actively working with Rhapsody,
therefore we're lacking the required knowledge and experience to create that format.

In case you use Rhapsody, we'd be most happy to accept any contribution from you,
we could include it on the arc42 download site and, of course, refer to you as author (if you like). 

In case you need any support, you can use either this issue or [the other arc42 channels](http://docs.arc42.org/contact/).

kind regards, Gernot

**Comment by ecsgz** [comment]
Hi Gernot, thank you for your reply and for the possibility for extension and contribution, this sounds good! Give me some time and I hope to get back to this and contribute directly with a first Rhapsody example format, if not already done by another person before...

Best regards, ecsgz

**Comment by nrnjnsk83** [comment]
Dear Gernot, ecsgz,
I am Niranjan SK you can address me as SK, SW architect @Bosch. We have a arc42 rhapsody profile established which can be used for both SW and System architecture. We have also established even the report generation based on IBM RPE. 
As an example we tried arc42 for arc42 within Rhapsody to explain the various views with report generation. 
We would like to contribute this profile template if this is still open

**Comment by gernotstarke** [comment]
Niranjan,

thanx for your offer. We (arc42.org) would include this profile in our download page on the arc42.org site.

I currently don't know of other organizations using Rhapsody with arc42, though... and I personally cannot test/use it as I don't have Rhapsody installed.

You could simply create a pull-request...

regards, Gernot

**Comment by nrnjnsk83** [comment]
Dear Gernot,
I tried creating a pull request, i am new to git-hub and looks like i am in a wrong branch. Could you please help me out to contribute and update the wiki

Regards
SK

**Comment by gernotstarke** [comment]
Dear SK, thanx for your pull-request, which actually did not contain your zip-file. 

I just created a "rhapsoy" subdirectory in the template repository:

**Fork** the arc42-template repository, 
and **checkout** the latest version of this repo to your local machine.

Switch to `master` branch: 
    
    git checkout master 

Then:
    
    cd ./arc42-template/other-formats/rhapsody

Then copy your files into the rhapsody directory (e.g. the zip-file containing everything).

Now you **add** and **commit** the new file(s):

    git add
    git commit -m "rhapsody template"

**Push** your local changes to your fork (which resides at Github):

    git push

Then you can create a pull-request against the arc42-template master repository...

Hope that makes it a little clearer for you...

kind regards,
Gernot

**Comment by nrnjnsk83** [comment]
Dear Gernot,

Thanks for the hints i managed to push the zip file on to the master branch. could you please verify? What about wiki is there any possibility for me to modify as well?

Regards
SK

**Comment by gernotstarke** [comment]
SK, you're not allowed to push onto the arc42-template master, you can only push to your personal fork of this repo...

Now you need to open a new pull request (from your fork to this repo)...

(reason is that only a few arc42-committers have rights to push changes...)

**Comment by nrnjnsk83** [comment]
Ha Okay Gernot, i pushed into my personal fork. No i created a pull request from my personal fork. Could you confirm whether you are able to push into arc42-template master after your review

**Comment by gernotstarke** [comment]
merged this PR into master!

will include it into the arc42.org <http://arc42.org/> downloads later today…

thanx,
Gernot

**Comment by nrnjnsk83** [comment]
Super thanks a lot!

**Comment by nrnjnsk83** [comment]
Dear Gernot,
Sorry, i forgot to mention Robert Bosch GmbH in my description. Could you please add Niranjan SK, Robert Bosch GmbH also in the download page some where.

Regards
SK

**Comment by gernotstarke** [comment]
done, you're mentioned in the Rhapsody download section...

**Comment by gernotstarke** [comment]
@ecsgz : please try out this latest contribution... I personally don't have access to a Rhapsody installation..

**Comment by nrnjnsk83** [comment]
Dear Gernot,
I cant see the link to download the rhapsody profile zip file in the Rhapsody download section. 

Regards
SK

**Comment by gernotstarke** [comment]
http://arc42.org/download#ibm-rhapsody-format

(it might happen that your browser caches on out-of-date version of the page)

**Comment by nrnjnsk83** [comment]
i am able to see the ibm-rhapsody-format but the link to zip file like how we have for EA is somehow not able to see.  I changed even the browser and it is the same, no link to download zip file like EA

**Comment by gernotstarke** [comment]
aaargh - sorry... my fault. will correct that asap...

**Comment by nrnjnsk83** [comment]
Cool! 
in my previous comment with regards to contribution, i meant more than my name Robert Bosch GmbH as a contributor would be better as this is a joint activity together here at Bosch. 
What is your opinion?

**Comment by gernotstarke** [comment]
both.

**Comment by gernotstarke** [comment]
fixed the download link + verified it works...
