### ISSUE TITLE
asciidoc template must be modified after download

### ISSUE THREAD

**Issue by johannes-brunner** [arc42/arc42-template#88]
If someone downloads the asciidoc template, then all the *.adoc files (except arc42-template.adoc) needs to be moved to a folder called src to generate a valid output document.
If you use the downloaded files directly as is, then you will get an error, because the include statements in ar42-template.adoc won't work out of the box.

Would be nice if the asciidoc template can be used as it is, without the need of modifications.

**Comment by rdmueller** [comment]
thanx for the reminder!

**Comment by rdmueller** [comment]
see also https://github.com/arc42/arc42-generator/issues/11
fixed, but I still want to test it...
