### ISSUE TITLE
html entity &rarr; leads to error with pdf generator

### ISSUE THREAD

**Issue by rdmueller** [arc42/arc42-template#89]
the english version of chapter 8 contains the html entity `&rarr;` which renders correct as HTML but leads to following error when using `asciidoctorj-pdf`:

`Failed to parse formatted text:`

I suggest to replace the entity with "=>" or just "=" as in the german version.

**Comment by gernotstarke** [comment]
changed to "=".

The underlying problem seems to result from asciidoctor itself... which can currently only parse 4- and 5-digit html entities...

**Comment by gernotstarke** [comment]
@rdmueller I did NOT generate a new download-release... I leave the pdf generation completely to you

**Comment by rdmueller** [comment]
thanx. will check it later today

**Comment by rdmueller** [comment]
all formats but confluence updated.

**Comment by rdmueller** [comment]
updated confluence pages at https://arc42-template.atlassian.net/wiki/
