### ISSUE TITLE
Plain contains hint to use Plain

### ISSUE THREAD

**Issue by sja** [arc42/arc42-template#90]
There is a Note at the first page, which tells to use the plain version. I think that should be only in the version with help.

**Comment by rdmueller** [comment]
good point

**Comment by gernotstarke** [comment]
Sebastian, I'm lost: On which "first page"? Could you please attach a screenshot... thx

**Comment by sja** [comment]
Sure, here is the German docx _Plain_ 1st page: https://www.dropbox.com/s/3llhrl4nq41omoy/Screenshot%202017-04-28%2017.23.02.png?dl=0
Note that  _**Note**_ :-)

**Comment by gernotstarke** [comment]
aah - now I understand. 
```
<schamloser-anwerbungsversuch>
Do you accidently want to become committer and fix it :-)
</schamloser-anwerbungsversuch>

```

**Comment by sja** [comment]
The problem is not the motivation but the time to do that.
Give me this weekend, maybe I can create a PR.

**Comment by gernotstarke** [comment]
intention appreciated :-)
