### ISSUE TITLE
Support for the ReStructuredText format 

### ISSUE THREAD

**Issue by schlauch** [arc42/arc42-template#93]
* https://en.wikipedia.org/wiki/ReStructuredText
* Is often used in the Python community together with Sphinx: http://www.sphinx-doc.org/en/stable/
* Sphinx is really interesting as it can glue together "normal" documentation and code comments. This is quite interesting as you can keep important information next to the code. But you can also "compile" it into your architecture documentation.

**Comment by gernotstarke** [comment]
Yeah, Sphinx is really well-known.

We definitely keep RST on our feature wishlist :-)

thanx for reminding us... (Tobias @schlauch , you may go forward and create a converter within our build-chain... in case of doubt,  @rdmueller might provide additional hints...)

**Comment by schlauch** [comment]
I would like to try. But it would be great if you could give me some hints about where to start...

**Comment by gernotstarke** [comment]
Tobias,

there are actually two repositories required for this task:

* THIS one (arc42-template), and
* the [arc42-generator](https://github.com/arc42/arc42-generator)

I'll try a short version (@rdmueller might correct me...)

* The generator includes the template as github sub-module... It's implemented around Gradle. 
* major portions are delegated to pandoc, a versatile (open-source) format converter.
* afaik, pandoc can generate rST from Asciidoc... 

The documentation of the generator-project is not perfect...
(you could writeup your experience and we add it to the faq.arc42.org documentation site...)

THANX for your interest!!

**Comment by schlauch** [comment]
Ok. Documentation is fine. It managed to clone and build it quite easily. Although I personally prefere the HTTPS URL for cloning.

In addition, I managed to locally create a "convert2rst" task. As pandoc directly supports rst, it is was quite easy to make it work. The only thing one needs to understand is that a specific localBuildDir.rst variable is only defined, if you add "rst" to formats defined in buildconfig.groovy.

I also checked the resulting format with an online rst viewer and it looks basically fine.

**Comment by schlauch** [comment]
Here is the corresponding pull request: https://github.com/arc42/arc42-generator/pull/16

**Comment by rdmueller** [comment]
Hey, this went quite well...
the new templates are available here:
https://github.com/arc42/arc42-template/tree/master/dist

@schlauch - do you use read the docs? Does it make sense to publish these new templates as example to read the docs?

**Comment by gernotstarke** [comment]
Ralf, you mean [ReadTheDocs](https://readthedocs.org/), don't you?

**Comment by gernotstarke** [comment]
I just updated http://arc42.org/downloads accordingly.

Added a short "format-overview" section to briefly explain the various download formats.

**Comment by gernotstarke** [comment]
Thanx @schlauch for adding rst support. Just updated the arc42.org/download page to include rst.

**Comment by rdmueller** [comment]
@gernotstarke yes, the ReadTheDocs website...

**Comment by schlauch** [comment]
@gernotstarke : No problem! It did not take so much time to make it work. Particularily, as I am already familiar with pandoc...

**Comment by schlauch** [comment]
@rdmueller: I know readthedocs more from the user perspective. But maybe it could be worth to put it there as an example. But in that case I would suggest to use the "with help" version....

**Comment by schlauch** [comment]
@gernotstarke : In the description of the rst format: "heavily used by [ReadTheDocs] and in the " => is the [ReadTheDocs] intentionally or should be a link to readthedocs??

**Comment by gernotstarke** [comment]
Yeah, should have been...

Seems I forgot...

Dr. Gernot Starke
+49-177-7282570
gs@gernotstarke.de
www.gernotstarke.de

Von einem mobilen Geraet gesendet - bitte verzeihen Sie eventuelle Tippfehler.

**Comment by gernotstarke** [comment]
fixed missing readTheDocs link.

**Comment by mbrunnen** [comment]
Thanks a lot for the RST template. I think sphinx is going to be the de-facto standard toolchain for documentation,
not only for python, e.g.: 
* CMake: https://cmake.org/cmake/help/latest/index.html
* Linux: https://www.kernel.org/doc/html/latest/

**Comment by gernotstarke** [comment]
thanx for the links!
